version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3304:3306
    environment:
      - MYSQL_DATABASE=cart
      - MYSQL_USER=cart
      - MYSQL_PASSWORD=cart
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
#  redis:
#    image: 'redis:latest'
#    ports:
#      - 6379:6379
